version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    build:
      context: . 
      dockerfile: .nginx.Dockerfile
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/ssl/:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
    command: /bin/sh -c "nginx -g 'daemon off;'"
    networks:
      - alkautsar

  lajuApi:
    container_name: lajuApi
    image: nestjs-api:1.0.0
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'
    depends_on:
      # - nginx
      - mariadb
    networks:
      - alkautsar

  lajuApp:
    container_name: lajuApp
    image: react-app:1.0.0
    build:
      context: ./../alkautsar-fe
      dockerfile: ./../alkautsar-fe/Dockerfile
    volumes:
      - ./../alkautsar-fe/src:/app/src
    env_file: ./../alkautsar-fe/.env
    ports:
      - '5173:5173'
    depends_on:
      - mariadb
    networks:
      - alkautsar
    
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=@lkauts4r
      - MYSQL_USER=sditalkautsar
      - MYSQL_DATABASE=alkautsar
    volumes:
      - mariadata:/var/lib/mysql:rw
      # - marialog:/var/lib/mysql/logs:rw
      - /var/docker/mariadb/conf:/etc/mysql
    ports:
      - '3306:3306'
    networks:
      - alkautsar

  redis:
    container_name: lajuredis
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redisdata:/bitnami/redis/data:rw
    ports:
      - '6379:6379'
    networks:
      - alkautsar

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare
    restart: unless-stopped
    networks:
      - alkautsar
    command: tunnel --config /etc/cloudflared/config.yml run UUID
    volumes:
      - ./cloudflared:/etc/cloudflared

networks: 
    alkautsar:
        driver: bridge

volumes:
  mariadata:
    driver: local
  marialog:
    driver: local
  redisdata:
    driver: local