version: '3'
services:
  proxy:
    image: nginx:latest
    container_name: proxy
    build:
      context: . 
      dockerfile: .nginx.Dockerfile
    # volumes:
    #   - ./nginx/conf.d/:/etc/nginx/conf.d
    #   - ./nginx/ssl/:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
    # command: /bin/sh -c "nginx -g 'daemon off;'"

  lajuApi:
    container_name: lajuApi
    image: nestjs-api:1.0.0
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'
    depends_on:
      - mariadb
      - proxy
      - redis

  lajuApp:
    container_name: lajuApp
    image: react-app:1.0.0
    build:
      context: ./../laju_investama
      dockerfile: ./../laju_investama/Dockerfile
    volumes:
      - ./../laju_investama/src:/app/src
    env_file: ./../laju_investama/.env
    ports:
      - '5173:5173'
    depends_on:
      - mariadb
      - proxy
      - redis
      - lajuApi
    
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=@lkauts4r
      - MYSQL_USER=sditalkautsar
      - MYSQL_DATABASE=alkautsar
    volumes:
      - mariadata:/var/lib/mysql:rw
      - /var/docker/mariadb/conf:/etc/mysql
    ports:
      - '3306:3306'

  redis:
    container_name: lajuredis
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redisdata:/bitnami/redis/data:rw
    ports:
      - '6379:6379'

volumes:
  mariadata:
    driver: local
  marialog:
    driver: local
  redisdata:
    driver: local